"""empty message

Revision ID: 2e59e58fbd75
Revises: 9695ccc2287c
Create Date: 2023-02-11 18:51:49.142986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e59e58fbd75'
down_revision = '9695ccc2287c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('properties', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'properties', ['properties'], ['id'])

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('properties_post_fkey', type_='foreignkey')
        batch_op.drop_column('post')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('properties_post_fkey', 'post', ['post'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('properties')

    # ### end Alembic commands ###
