"""empty message

Revision ID: 420a68ca53f9
Revises: 
Create Date: 2023-02-16 00:44:07.842024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420a68ca53f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.String(length=3000), nullable=False),
    sa.Column('categories', sa.Integer(), nullable=False),
    sa.Column('event', sa.Boolean(), nullable=False),
    sa.Column('alwaysAvailable', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.String(length=200), nullable=False),
    sa.Column('certificate', sa.Boolean(), nullable=False),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default='2023-02-16 00:44:06.805841', nullable=True),
    sa.ForeignKeyConstraint(['categories'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
