"""empty message

Revision ID: 62b9c9a5af43
Revises: 4aca9810495c
Create Date: 2023-02-23 18:30:46.833184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62b9c9a5af43'
down_revision = '4aca9810495c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('publishertype',
               existing_type=postgresql.ENUM('university', 'academy', 'company', 'independent', 'other', name='publishertype'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('publishertype',
               existing_type=postgresql.ENUM('university', 'academy', 'company', 'independent', 'other', name='publishertype'),
               nullable=False)

    # ### end Alembic commands ###
