"""empty message

Revision ID: 8768a872ce88
Revises: 126d1358bda8
Create Date: 2023-02-26 00:01:25.259556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8768a872ce88'
down_revision = '126d1358bda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_table('following')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='following_followed_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='following_pkey')
    )
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    # ### end Alembic commands ###
