"""empty message

Revision ID: 9695ccc2287c
Revises: cbe6dab2036e
Create Date: 2023-02-11 18:47:31.439417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9695ccc2287c'
down_revision = 'cbe6dab2036e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_post_fkey', type_='foreignkey')
        batch_op.drop_column('post')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['categories'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categories')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('categories_post_fkey', 'post', ['post'], ['id'])

    # ### end Alembic commands ###
