"""empty message

Revision ID: cbe6dab2036e
Revises: b0e172b3d9cb
Create Date: 2023-02-11 18:37:35.026423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe6dab2036e'
down_revision = 'b0e172b3d9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('post_author_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('certificate', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('certificate')
        batch_op.drop_column('duration')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_author_fkey', 'user', ['author'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
