"""empty message

Revision ID: f9f6d1e9a255
Revises: 2787db4163be
Create Date: 2023-02-27 21:12:29.278141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9f6d1e9a255'
down_revision = '2787db4163be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('publisherMode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('publishertype',
               existing_type=postgresql.ENUM('university', 'academy', 'company', 'independent', 'other', name='publishertype'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('publishertype',
               existing_type=postgresql.ENUM('university', 'academy', 'company', 'independent', 'other', name='publishertype'),
               nullable=False)
        batch_op.alter_column('publisherMode',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
